# safelist
branches:
  only:
  - master
  
language: python

python:
 - 3

install: 
 - pip install -r requirements.txt

before_script:
- git config --global user.email "ferreol.soulez@univ-lyon1.fr"
- git config --global user.name "ferreolS"



script:
- cd Doc
- mkdir build
- cd build
- git clone https://github.com/Biomedical-Imaging-Group/GlobalBioIm.git html
- cd html
- git symbolic-ref HEAD refs/heads/gh-pages  # auto-switches branches to gh-pages
- rm .git/index
- git clean -fdx
- cd ../..
- make html

after_success:
- cd build/html
- touch .nojekyll
- git add *
- git add .nojekyll 
- git commit -a -m "Add Doc"
- git push --force  https://${GH_TOKEN}@github.com/Biomedical-Imaging-Group/GlobalBioIm.git  gh-pages 


